{% set version = "2.0.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rfast
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rfast_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rfast/Rfast_{{ version }}.tar.gz
  sha256: 1bb2c8f0580d0fe27e2b06d1dd069d09588f410e4a895147cca445f32092c4b0

build:
  merge_build_host: true  # [win]
  skip: true              # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-rcppziggurat               # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-rcpparmadillo
    - r-rcppziggurat
    - libblas
    - liblapack
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.3
    - r-rcpparmadillo
    - r-rcppziggurat

test:
  commands:
    - $R -e "library('Rfast')"           # [not win]
    - "\"%R%\" -e \"library('Rfast')\""  # [win]

about:
  home: https://github.com/RfastOfficial/Rfast
  license: GPL-2.0-or-later
  summary: 'A collection of fast (utility) functions for data analysis. Column- and row- wise means, medians, variances, minimums, maximums, many t, F and G-square tests, many regressions (normal, logistic, Poisson), are some of the many fast functions. Reference: Tsagris M, Papadakis M. (2018). Taking R to its limits: 70+
    tips. PeerJ Preprints 6:e26605v1 <doi:10.7287/peerj.preprints.26605v1>.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
