{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rfast
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rfast_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rfast/Rfast_{{ version }}.tar.gz
  sha256: be8f57afe4a345b2404e0491b2441ec856779888c7db0fe072dbab2d60a90d04

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-rcpparmadillo
    - r-rcppziggurat
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.3
    - r-rcpparmadillo
    - r-rcppziggurat

test:
  commands:
    - $R -e "library('Rfast')"           # [not win]
    - "\"%R%\" -e \"library('Rfast')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rfast
  license: GPL-2.0-or-later
  summary: 'A collection of fast (utility) functions for data analysis. Column- and row- wise means, medians, variances, minimums, maximums, many t, F and G-square tests, many regressions (normal, logistic, Poisson), are some of the many fast functions. Reference: Tsagris M, Papadakis M. (2018). Taking R to its limits: 70+
    tips. PeerJ Preprints 6:e26605v1 <doi:10.7287/peerj.preprints.26605v1>.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Rfast
# Type: Package
# Title: A Collection of Efficient and Extremely Fast R Functions
# Version: 1.9.5
# Date: 2019-07-06
# Author: Manos Papadakis, Michail Tsagris, Marios Dimitriadis, Stefanos Fafalios, Ioannis Tsamardinos, Matteo Fasiolo, Giorgos Borboudakis, John Burkardt, Changliang Zou, Kleanthi Lakiotaki and Christina Chatzipantsiou.
# Maintainer: Manos Papadakis <rfastofficial@gmail.com>
# Depends: R (>= 3.5.0), Rcpp (>= 0.12.3), RcppZiggurat
# LinkingTo: Rcpp (>= 0.12.3), RcppArmadillo
# SystemRequirements: C++11
# Description: A collection of fast (utility) functions for data analysis. Column- and row- wise means, medians, variances, minimums, maximums, many t, F and G-square tests, many regressions (normal, logistic, Poisson), are some of the many fast functions. Reference: Tsagris M, Papadakis M. (2018). Taking R to its limits: 70+ tips. PeerJ Preprints 6:e26605v1 <doi:10.7287/peerj.preprints.26605v1>.
# License: GPL (>= 2.0)
# LazyData: TRUE
# NeedsCompilation: yes
# Packaged: 2019-07-08 15:41:38 UTC; MANOS
# Repository: CRAN
# Date/Publication: 2019-07-12 12:02:41 UTC
