appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: py2VMMVQ1rxuSe9YeAyx26dr3D8scT37rmLhqCNsImET4ENiA+RR4ZflqebU7Lc56RpSqkux2VQpJvIWK6FT7ABtbq1EpO+lKF0XdGe4HgFL/6YludOb/fCd2uPrAJGI60GLl/xp9LgyeHi04IbTiT065Kc9j043/tirf5HRoWdILzOZW78smB5q+Vz+JLv7bOnUUihC7SwlTfZ3AMtTtd7PElHABXs/+BsjVtjx8lCARQx0hAt6p0PIN2PjKsbrMcFPgWWw5WS0kGWsU311sxZjl7SgkQxZzk+ansoxxwnoEe1uD9Gi38+XA3ofogUq3jQghG8/iHuD/FQn089s0fWEIK5IPfkyECGlzFbFEsxk6SUAqQAnGEf68Z0CQJ8joygTjjfk+MSUqyayf58HmNM7hTc9BDIj4giEREwQtR3WrfbYlJmp2hxF/fT/M0Eb46lpICit99JM6vlI1038ZTHapgF1M0qdpgur1FsKQHtl4qCzsXu74PJXtAcvQp3tKFIqqk2vm3/FhBmaMv1A+pIL0dnU9RLTa/7YePdigBNeDZhK7Z0tvOWwO92PyOgyYnc5/5xPAeXA0cxjzncZJjVWVwPNcw6YdDmLqGpKD2wNy2ZVmXhXZqiJLGA6Kgv+FIjoaIUxiP9rwB8Fj7e9xJfOneEfZQMd6Ykk9aTZa04=
